[book]
authors = ["Marc LaFountain"]
language = "en"
multilingual = false
src = "./src"
title = "Orion Docs"

[output.html]
edit-url-template = "https://github.com/kagisearch/kagi-docs/edit/main/orion/{path}"
site-url = "/orion/"
additional-css = ["patch.css"]
fold = {enable = true, level= 0}

[output.html.font]
enable = false

