[book]
authors = ["Marc LaFountain"]
language = "en"
multilingual = false
src = "./src"
title = "Kagi Search User Guide"

[build]
create-missing = false

[output.html]
edit-url-template = "https://github.com/kagisearch/kagi-docs/edit/main/kagi/{path}"
site-url = "/kagi/"
additional-css = ["patch.css"]
fold = {enable = true, level= 0}

[output.html.font]
enable = false
