name: Build test

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  buildtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        tags: "test-kagi-docs:latest"
        push: false
